default_platform(:android)

platform :android do
  desc "Upload one signed Android bundle to a Google Play track"
  lane :upload_bundle do |options|
    required_options = %i[aab json_key package_name track]
    required_options.each do |name|
      UI.user_error!("Missing required option: #{name}") if options[name].to_s.empty?
    end

    aab = File.expand_path(options[:aab])
    json_key = File.expand_path(options[:json_key])

    UI.user_error!("Android App Bundle not found: #{aab}") unless File.file?(aab)
    UI.user_error!("Google Play key not found: #{json_key}") unless File.file?(json_key)

    upload_to_play_store(
      aab: aab,
      json_key: json_key,
      package_name: options[:package_name],
      track: options[:track],
      release_status: options.fetch(:release_status, "draft"),
      validate_only: options.fetch(:validate_only, false).to_s == "true",
      skip_upload_metadata: true,
      skip_upload_images: true,
      skip_upload_screenshots: true,
      skip_upload_changelogs: true,
    )
  end
end
